[package]
name = "lazer-exporter"
version = "0.1.5"
description = "Export osu!lazer beatmap sets to .osz files"
authors = ["ATRI1024"]
edition = "2021"

[lib]
name = "lazer_exporter_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
realm-db-reader = { git = "https://github.com/Ohdmire/realm-db-reader" }
osu-db = "0.2.1"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
base64 = "0.22"
sha2 = "0.10"
walkdir = "2"
zip = { version = "4", default-features = false, features = ["deflate"] }
tokio = { version = "1", features = ["fs", "rt-multi-thread"] }
rayon = "1.12.0"

[profile.release]
strip = true
lto = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3.27.0"

[target.'cfg(windows)'.dependencies.winreg]
version = "0.55"
